[package]
name = "memtest-vulkan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
erupt = "0.16"
inline-spirv = { version = "0.1", features = ["glsl"] }
bytemuck = "1.4"

