#!/usr/bin/env -Scargo run --release --manifest-path
#cargo fmt
#cargo build --release --target x86_64-pc-windows-gnu
[package]
edition = '2021'
name = 'memtest_vulkan'
version = '0.0.3'

[dependencies]
byte-strings = '0.2.2'
ctrlc = '3.2.2'
mortal = '0.2.3'

[dependencies.erupt]
default-features = false
features = ['loading']
version = '0.22'

[dependencies.memtest_vulkan_build]
path = './memtest_vulkan_build'

[workspace]
members = ['memtest_vulkan_build']

# produce small file size release builds
[profile.release]
codegen-units = 1
lto = true
strip = true
