#!/usr/bin/env -Scargo run --release --manifest-path
[package]
name = "memtest-vulkan"
version = "0.0.1"
edition = "2021"


[dependencies]
erupt = { version = "0.22", default-features = false, features = ["loading"] }
inline-spirv = { version = "0.1", default-features = false, features = ["glsl", "build-from-source"] }

[profile.release]
# produce small file size release builds
strip = true
lto = true
codegen-units = 1
