[package]
name = "memtest-vulkan"
version = "0.0.1"
edition = "2021"


[dependencies]
gpu-alloc = { version = "0.5", default-features = false}
gpu-alloc-erupt = { version = "0.7", default-features = false}
erupt = { version = "0.22", default-features = false, features = ["loading"] }
inline-spirv = { version = "0.1", default-features = false, features = ["glsl", "build-from-source"] }
bytemuck = "1.4"

[profile.release]
# produce small file size release builds
strip = true
lto = true
codegen-units = 1
