[package]
edition = '2021'
name = 'memtest_vulkan_build'
version = '0.0.0'

[dependencies]
quote = '1.0'
syn = '1.0'

[dependencies.naga]
default-features = false
features = [
    'wgsl-in',
    'spv-out',
]
version = '0.9'

[lib]
proc-macro = true
