[package]
name = "memtest_vulkan_build"
version = "0.0.0"
edition = "2021"

[dependencies]
syn = "1.0"
quote = "1.0"
naga = { version = "0.9", default-features = false, features = ["wgsl-in", "spv-out"]}

[lib]
proc-macro = true
