name: ci
on:
  push:
    branches: [ main ]
    tags:
      - '**'
  pull_request:
    branches: [ main ]
jobs:
  build-in-docker-job:
    runs-on: ubuntu-22.04
    container: ghcr.io/galkinvv/manycross2014:rust-1.64
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-in-docker
      - uses: actions/upload-artifact@v3
        with:
          name: Windows .exe
          path: target/artifacts/*.exe
      - uses: actions/upload-artifact@v3
        with:
          name: Linux binaries (x86_64 and aarch64)
          path: target/artifacts/*linux*
